import { Document, Page, Text, View, StyleSheet, renderToBuffer } from "@react-pdf/renderer";
import type { CompanyResearchResult } from "./types";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 10, fontFamily: "Helvetica", color: "#1a1a1a" },
  header: { marginBottom: 20, borderBottomWidth: 2, borderBottomColor: "#0e1116", paddingBottom: 12 },
  companyName: { fontSize: 22, fontWeight: 700, marginBottom: 4 },
  website: { fontSize: 11, color: "#2e6b62" },
  contactRow: { flexDirection: "row", marginTop: 8, fontSize: 9, color: "#555555" },
  contactItem: { marginRight: 20 },
  section: { marginBottom: 16 },
  sectionTitle: {
    fontSize: 11,
    fontWeight: 700,
    marginBottom: 6,
    textTransform: "uppercase",
    color: "#333333",
    letterSpacing: 0.5,
  },
  paragraph: { fontSize: 10, lineHeight: 1.5 },
  chipsRow: { flexDirection: "row", flexWrap: "wrap" },
  chip: {
    fontSize: 9,
    paddingVertical: 3,
    paddingHorizontal: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#cccccc",
    marginRight: 6,
    marginBottom: 6,
  },
  bulletItem: { flexDirection: "row", marginBottom: 4 },
  bulletDash: { width: 12, fontSize: 10 },
  bulletText: { flex: 1, fontSize: 10, lineHeight: 1.4 },
  competitorRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#eeeeee",
  },
  competitorName: { fontSize: 10, fontWeight: 700 },
  competitorSite: { fontSize: 9, color: "#555555" },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 40,
    right: 40,
    fontSize: 8,
    color: "#999999",
    borderTopWidth: 1,
    borderTopColor: "#eeeeee",
    paddingTop: 8,
  },
});

function CompanyReportDocument({ data }: { data: CompanyResearchResult }) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <View style={styles.header}>
          <Text style={styles.companyName}>{data.companyName}</Text>
          <Text style={styles.website}>{data.website}</Text>
          {(data.phone || data.address) && (
            <View style={styles.contactRow}>
              {data.phone && <Text style={styles.contactItem}>Phone: {data.phone}</Text>}
              {data.address && <Text style={styles.contactItem}>Address: {data.address}</Text>}
            </View>
          )}
        </View>

        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Company Summary</Text>
          <Text style={styles.paragraph}>{data.summary}</Text>
        </View>

        {data.productsServices.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Products &amp; Services</Text>
            <View style={styles.chipsRow}>
              {data.productsServices.map((item) => (
                <Text key={item} style={styles.chip}>
                  {item}
                </Text>
              ))}
            </View>
          </View>
        )}

        {data.painPoints.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>AI-Generated Pain Points</Text>
            {data.painPoints.map((point) => (
              <View key={point} style={styles.bulletItem}>
                <Text style={styles.bulletDash}>-</Text>
                <Text style={styles.bulletText}>{point}</Text>
              </View>
            ))}
          </View>
        )}

        {data.competitors.length > 0 && (
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Competitor Analysis</Text>
            {data.competitors.map((c) => (
              <View key={c.website} style={styles.competitorRow}>
                <Text style={styles.competitorName}>{c.name}</Text>
                <Text style={styles.competitorSite}>{c.website}</Text>
              </View>
            ))}
          </View>
        )}

        <Text style={styles.footer}>
          Generated by Company Research Agent — {new Date().toLocaleDateString()}
        </Text>
      </Page>
    </Document>
  );
}

export async function renderCompanyReportPdf(data: CompanyResearchResult): Promise<Buffer> {
  return renderToBuffer(<CompanyReportDocument data={data} />);
}